title: "KoDF: A Large-scale Korean DeepFake Detection Dataset"
description: "Authors: Patrick Kwon<sup>*</sup>, Jaeseong You<sup>*</sup>, Gyuhyeon Nam, Sungwoo Park, Gyeongsu Chae<br><font size='1'><sup>*</sup> Equal contribution  </font><br>ArXiv: arXiv:2103.10094"
show_downloads: true
google_analytics:
theme: jekyll-theme-architect